# Generated by Django 6.0 on 2026-03-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0004_seed_subscription_plans"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("BKASH", "bKash"),
                            ("NAGAD", "Nagad"),
                            ("ROCKET", "Rocket"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Display label, e.g. 'bKash Send Money'",
                        max_length=200,
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        help_text="Payment details — number, account name, branch, etc."
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Emoji or short icon text", max_length=10
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "payment info",
                "verbose_name_plural": "payment info",
                "db_table": "apps_payment_info",
                "ordering": ["display_order"],
            },
        ),
    ]
