# Generated by Django 6.0 on 2026-03-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0005_add_payment_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("TRIAL", "Trial"),
                    ("INACTIVE", "Inactive"),
                    ("ACTIVE", "Active"),
                    ("EXPIRED", "Expired"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="TRIAL",
                max_length=20,
            ),
        ),
    ]
