# Generated by Django 6.0.2 on 2026-03-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0007_payment_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="cancel_at_period_end",
            field=models.BooleanField(
                default=False,
                help_text="If true, subscription will be cancelled at next billing date",
            ),
        ),
    ]
