# Generated by Django 6.0.2 on 2026-03-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0008_subscription_cancel_at_period_end"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="available_ai_credits",
            field=models.IntegerField(
                default=0,
                help_text="Remaining AI credits for the current billing period",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="monthly_ai_credits",
            field=models.IntegerField(
                default=0,
                help_text="AI credits included per month, 0 means no AI access",
            ),
        ),
    ]
