# Generated by Django 6.0.2 on 2026-04-03 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_subscription_available_ai_credits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='target_plan',
            field=models.ForeignKey(blank=True, help_text='If set, subscription upgrades to this plan upon payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='subscriptions.subscriptionplan'),
        ),
    ]
