# Generated by Django 6.0 on 2026-04-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0011_add_gateway_invoice_id_to_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="payment_application_snapshot",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Subscription state before this invoice was applied",
            ),
        ),
    ]
