# Generated by Django 6.0.2 on 2026-04-19 08:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_backfill_missing_ai_plan_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='credit_applied',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Amount of credit from center's balance applied to this invoice", max_digits=10),
        ),
    ]
