# Generated by Django 6.0 on 2026-04-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_add_credit_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Invoice amount before any credit was applied', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Remaining amount after credit applied', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('BKASH', 'bKash'), ('NAGAD', 'Nagad'), ('ONLINE', 'Online Gateway'), ('BANK_TRANSFER', 'Bank Transfer'), ('CREDIT', 'Credit Balance')], max_length=20),
        ),
    ]
