# Generated by Django 6.0.2 on 2026-03-20 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_invoice_payment_invoice_invoiceitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="walk_in_name",
            field=models.CharField(
                blank=True,
                help_text="Name for walk-in patients (no registration)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="walk_in_phone",
            field=models.CharField(
                blank=True, help_text="Phone for walk-in patients", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                help_text="Registered patient (optional for walk-ins)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
