# Generated by Django 6.0 on 2026-03-29 08:56

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_invoice_paid_at_and_snapshots(apps, schema_editor):
    Invoice = apps.get_model("payments", "Invoice")

    paid_invoices = Invoice.objects.filter(
        status="PAID",
        paid_at__isnull=True,
    )
    for invoice in paid_invoices.iterator():
        invoice.paid_at = invoice.created_at
        if invoice.referrer_id and not invoice.referrer_name_snapshot:
            invoice.referrer_name_snapshot = invoice.referrer.name
        if invoice.referrer_id and not invoice.commission_pct_snapshot:
            invoice.commission_pct_snapshot = invoice.referrer.commission_pct
        invoice.save(
            update_fields=[
                "paid_at",
                "referrer_name_snapshot",
                "commission_pct_snapshot",
            ]
        )


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0005_add_invoice_audit_log"),
        ("tenants", "0024_add_verify_reports_permission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Referrer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name of the referrer", max_length=200
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Contact phone number",
                        max_length=20,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("DOCTOR", "Doctor"),
                            ("AGENT", "Agent"),
                            ("CORPORATE", "Corporate"),
                            ("OTHER", "Other"),
                        ],
                        default="DOCTOR",
                        help_text="Classification of the referrer",
                        max_length=20,
                    ),
                ),
                (
                    "commission_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Default commission percentage (0-100)",
                        max_digits=5,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive doctors are hidden from the dropdown",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrers",
                        to="tenants.diagnosticcenter",
                    ),
                ),
            ],
            options={
                "verbose_name": "referrer",
                "verbose_name_plural": "referrers",
                "db_table": "apps_referrer",
                "ordering": ["name"],
                "unique_together": {("center", "name", "phone")},
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="commission_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Computed: total × commission_pct_snapshot / 100",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="commission_pct_snapshot",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Frozen commission percentage copied to the invoice",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="paid_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the invoice became paid and commission-eligible",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="referrer",
            field=models.ForeignKey(
                blank=True,
                help_text="External referrer who earns commission",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="payments.referrer",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="referrer_name_snapshot",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Frozen referrer name copied to the invoice",
                max_length=200,
            ),
        ),
        migrations.CreateModel(
            name="ReferrerSettlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "settlement_number",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated settlement number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount paid in this settlement",
                        max_digits=10,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("BKASH", "bKash"),
                            ("NAGAD", "Nagad"),
                            ("BANK", "Bank"),
                            ("OTHER", "Other"),
                        ],
                        default="CASH",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "paid_at",
                    models.DateTimeField(help_text="When the payment was made"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrer_settlements",
                        to="tenants.diagnosticcenter",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrer_settlements_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlements",
                        to="payments.referrer",
                    ),
                ),
            ],
            options={
                "verbose_name": "referrer settlement",
                "verbose_name_plural": "referrer settlements",
                "db_table": "apps_referrer_settlement",
                "ordering": ["-paid_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReferrerSettlementItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrer_settlement_items",
                        to="payments.invoice",
                    ),
                ),
                (
                    "settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="payments.referrersettlement",
                    ),
                ),
            ],
            options={
                "verbose_name": "referrer settlement item",
                "verbose_name_plural": "referrer settlement items",
                "db_table": "apps_referrer_settlement_item",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="referrersettlementitem",
            constraint=models.UniqueConstraint(
                fields=("settlement", "invoice"),
                name="unique_settlement_invoice_allocation",
            ),
        ),
        migrations.AddConstraint(
            model_name="referrersettlementitem",
            constraint=models.CheckConstraint(
                condition=models.Q(allocated_amount__gt=Decimal("0.00")),
                name="referrer_allocated_amount_gt_zero",
            ),
        ),
        migrations.RunPython(
            backfill_invoice_paid_at_and_snapshots,
            migrations.RunPython.noop,
        ),
    ]
