services:
  db:
    image: postgres:16-alpine
    container_name: lablink_postgres
    environment:
      POSTGRES_DB: lablink
      POSTGRES_USER: lablink_user
      POSTGRES_PASSWORD: lablink_password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lablink_user -d lablink"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: lablink_redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  celery_worker:
    build: .
    container_name: lablink_celery_worker
    command: celery -A core worker --loglevel=info
    working_dir: /app/src
    volumes:
      - .:/app
    env_file:
      - env/.env
    environment:
      - POSTGRES_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery_beat:
    build: .
    container_name: lablink_celery_beat
    command: celery -A core beat --loglevel=info
    working_dir: /app/src
    volumes:
      - .:/app
    env_file:
      - env/.env
    environment:
      - POSTGRES_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:
