# Generated by Django 6.0.2 on 2026-03-15 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_add_phone_number_and_patient_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['id'], 'verbose_name': 'staff', 'verbose_name_plural': 'staff'},
        ),
    ]
