# Generated by Django 6.0.2 on 2026-03-15 15:06
# Manually edited to include data migration for RBAC.

import django.db.models.deletion
from django.db import migrations, models


# ── Seed Data ─────────────────────────────────────────────────────

PERMISSIONS = [
    # (codename, name, category)
    ('view_patients', 'View Patients', 'Patients'),
    ('manage_patients', 'Manage Patients', 'Patients'),
    ('view_appointments', 'View Appointments', 'Appointments'),
    ('manage_appointments', 'Manage Appointments', 'Appointments'),
    ('view_reports', 'View Reports', 'Reports'),
    ('create_reports', 'Create Reports', 'Reports'),
    ('manage_reports', 'Manage Reports', 'Reports'),
    ('view_test_orders', 'View Test Orders', 'Test Orders'),
    ('manage_test_orders', 'Manage Test Orders', 'Test Orders'),
    ('view_payments', 'View Payments', 'Payments'),
    ('manage_payments', 'Manage Payments', 'Payments'),
    ('view_staff', 'View Staff', 'Staff'),
    ('manage_staff', 'Manage Staff', 'Staff'),
    ('view_doctors', 'View Doctors', 'Doctors'),
    ('manage_doctors', 'Manage Doctors', 'Doctors'),
    ('view_analytics', 'View Analytics', 'Analytics'),
    ('manage_settings', 'Manage Settings', 'Settings'),
    ('view_roles', 'View Roles', 'Roles'),
    ('manage_roles', 'Manage Roles', 'Roles'),
]

DEFAULT_ROLES = {
    # role_name: list of permission codenames (None = all)
    'Admin': None,
    'Lab Technician': [
        'view_patients', 'view_reports', 'create_reports',
        'manage_reports', 'view_test_orders', 'manage_test_orders',
    ],
    'Receptionist': [
        'view_patients', 'manage_patients',
        'view_appointments', 'manage_appointments',
        'view_payments',
    ],
}

# Map old CharField values to new role names
OLD_ROLE_MAP = {
    'ADMIN': 'Admin',
    'LAB_TECHNICIAN': 'Lab Technician',
    'RECEPTIONIST': 'Receptionist',
}


def seed_permissions_and_roles(apps, schema_editor):
    """Create all permissions, then create default roles for each center."""
    Permission = apps.get_model('tenants', 'Permission')
    Role = apps.get_model('tenants', 'Role')
    DiagnosticCenter = apps.get_model('tenants', 'DiagnosticCenter')

    # Create permissions
    perm_objects = {}
    for codename, name, category in PERMISSIONS:
        perm, _ = Permission.objects.get_or_create(
            codename=codename,
            defaults={'name': name, 'category': category},
        )
        perm_objects[codename] = perm

    # Create default roles for each center
    for center in DiagnosticCenter.objects.all():
        for role_name, perm_codenames in DEFAULT_ROLES.items():
            role, _ = Role.objects.get_or_create(
                name=role_name,
                center=center,
                defaults={'is_system': True},
            )
            if perm_codenames is None:
                role.permissions.set(perm_objects.values())
            else:
                role.permissions.set(
                    [perm_objects[c] for c in perm_codenames]
                )


def migrate_staff_roles(apps, schema_editor):
    """Convert old Staff.role_old CharField to new Role FK."""
    Staff = apps.get_model('tenants', 'Staff')
    Role = apps.get_model('tenants', 'Role')

    for staff in Staff.objects.select_related('center').all():
        old_value = staff.role_old
        new_role_name = OLD_ROLE_MAP.get(old_value, old_value)
        try:
            role = Role.objects.get(name=new_role_name, center=staff.center)
        except Role.DoesNotExist:
            # Fallback: create the role
            role, _ = Role.objects.get_or_create(
                name=new_role_name,
                center=staff.center,
                defaults={'is_system': False},
            )
        staff.role = role
        staff.save(update_fields=['role'])


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_staff_ordering'),
    ]

    operations = [
        # 1. Create Permission table
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(help_text='Programmatic identifier, e.g. view_reports', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable name, e.g. View Reports', max_length=150)),
                ('category', models.CharField(help_text='Grouping category for UI, e.g. Reports', max_length=50)),
            ],
            options={
                'verbose_name': 'permission',
                'verbose_name_plural': 'permissions',
                'db_table': 'core_permission',
                'ordering': ['category', 'codename'],
            },
        ),
        # 2. Create Role table
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_system', models.BooleanField(default=False, help_text='System roles cannot be deleted.')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='tenants.diagnosticcenter')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='tenants.permission')),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'db_table': 'core_role',
                'ordering': ['name'],
                'unique_together': {('name', 'center')},
            },
        ),
        # 3. Seed permissions and default roles
        migrations.RunPython(seed_permissions_and_roles, migrations.RunPython.noop),
        # 4. Rename old role column
        migrations.RenameField(
            model_name='staff',
            old_name='role',
            new_name='role_old',
        ),
        # 5. Add new FK column (nullable initially)
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='staff_members',
                to='tenants.role',
            ),
        ),
        # 6. Migrate data
        migrations.RunPython(migrate_staff_roles, migrations.RunPython.noop),
        # 7. Remove old column
        migrations.RemoveField(
            model_name='staff',
            name='role_old',
        ),
        # 8. Make FK non-nullable
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='staff_members',
                to='tenants.role',
            ),
        ),
    ]
