# Generated by Django 6.0.2 on 2026-03-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0012_user_center_fk_and_doctor_m2m_removal"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosticcenter",
            name="allow_online_appointments",
            field=models.BooleanField(
                default=False,
                help_text="Whether patients can self-book appointments online.",
            ),
        ),
    ]
