# Generated by Django 6.0 on 2026-03-20 02:30

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0015_add_bengali_language_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosticcenter",
            name="doctor_visit_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Default doctor consultation / visit fee for this center",
                max_digits=10,
            ),
        ),
    ]
