# Generated by Django 6.0.2 on 2026-03-20 04:58

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0016_diagnosticcenter_doctor_visit_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="visit_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Doctor consultation / visit fee",
                max_digits=10,
            ),
        ),
    ]
