# Generated by Django 6.0.2 on 2026-03-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0017_doctor_visit_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosticcenter",
            name="paper_size",
            field=models.CharField(
                choices=[
                    ("A4", "A4 (210 × 297 mm)"),
                    ("A5", "A5 (148 × 210 mm)"),
                    ("Letter", "Letter (216 × 279 mm)"),
                ],
                default="A4",
                help_text="Paper size for printing invoices and reports",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="print_footer_margin_mm",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Bottom margin in mm to skip for pre-printed footer",
            ),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="print_header_margin_mm",
            field=models.PositiveIntegerField(
                default=0, help_text="Top margin in mm to skip for pre-printed header"
            ),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="use_preprinted_paper",
            field=models.BooleanField(
                default=False,
                help_text="Hide digital header/footer when printing (for pre-printed letterhead paper)",
            ),
        ),
    ]
