# Generated by Django 6.0 on 2026-03-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0019_doctor_schedule_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosticcenter",
            name="email_notifications_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Send email notifications to patients on report verification",
            ),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="sms_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Send SMS notifications to patients on report verification",
            ),
        ),
    ]
