# Generated by Django 6.0.2 on 2026-03-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0024_add_verify_reports_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosticcenter",
            name="send_email_invoice",
            field=models.BooleanField(
                default=False,
                help_text="Send email receipt to patient when invoice is created",
            ),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="send_sms_invoice",
            field=models.BooleanField(
                default=False,
                help_text="Send SMS receipt to patient when invoice is created",
            ),
        ),
    ]
