# Generated by Django 6.0.2 on 2026-03-30 10:59

from django.db import migrations

NEW_PERMISSIONS = [
    ("send_sms", "Global SMS Capability", "Feature Entitlements"),
    ("send_email", "Global Email Capability", "Feature Entitlements"),
    (
        "use_ai_features",
        "Use AI Features (Report Extraction, Chatbot)",
        "Feature Entitlements",
    ),
]


def add_premium_permissions(apps, _schema_editor):
    Permission = apps.get_model("tenants", "Permission")
    Role = apps.get_model("tenants", "Role")
    DiagnosticCenter = apps.get_model("tenants", "DiagnosticCenter")

    perm_objs = []
    for codename, name, category in NEW_PERMISSIONS:
        perm, _ = Permission.objects.get_or_create(
            codename=codename,
            defaults={"name": name, "category": category},
        )
        perm_objs.append(perm)

    # Automatically grant these to "Admin" role for convenience
    for role in Role.objects.filter(name="Admin"):
        role.permissions.add(*perm_objs)


def remove_premium_permissions(apps, _schema_editor):
    Permission = apps.get_model("tenants", "Permission")
    Permission.objects.filter(
        codename__in=["send_sms", "send_email", "use_ai_features"],
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0025_diagnosticcenter_send_email_invoice_and_more"),
    ]

    operations = [
        migrations.RunPython(
            add_premium_permissions,
            reverse_code=remove_premium_permissions,
        ),
    ]
