# Generated by Django 6.0.2 on 2026-03-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0026_premium_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosticcenter",
            name="can_use_ai",
            field=models.BooleanField(
                default=False,
                help_text="Superadmin: unlock AI features for this center",
            ),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="can_use_email",
            field=models.BooleanField(
                default=False,
                help_text="Superadmin: unlock Email capability for this center",
            ),
        ),
        migrations.AddField(
            model_name="diagnosticcenter",
            name="can_use_sms",
            field=models.BooleanField(
                default=False,
                help_text="Superadmin: unlock SMS capability for this center",
            ),
        ),
    ]
