# Generated by Django 6.0 on 2026-04-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0031_remove_resend_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosticcenter",
            name="has_used_trial",
            field=models.BooleanField(
                default=False,
                help_text="Whether this center has previously used a free trial",
            ),
        ),
    ]
