# Generated by Django 6.0.2 on 2026-04-19 08:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0032_add_has_used_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticcenter',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Credit balance from plan downgrades, refunds, etc. Applied to future invoices.', max_digits=10),
        ),
    ]
