# Generated by Django 6.0 on 2026-03-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("followups", "0002_add_manage_followups_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followup",
            name="reason",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
