# Generated by Django 6.0.2 on 2026-03-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("CONFIRMED", "Confirmed"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="CONFIRMED",
                max_length=20,
            ),
        ),
    ]
