# Generated by Django 6.0.2 on 2026-03-05 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0003_initial"),
        ("diagnostics", "0003_initial"),
        ("tenants", "0006_add_phone_number_and_patient_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="centertestpricing",
            options={
                "verbose_name": "center test pricing",
                "verbose_name_plural": "center test pricings",
            },
        ),
        migrations.AlterModelOptions(
            name="report",
            options={"verbose_name": "report", "verbose_name_plural": "reports"},
        ),
        migrations.AlterModelOptions(
            name="testtype",
            options={"verbose_name": "test type", "verbose_name_plural": "test types"},
        ),
        migrations.AddField(
            model_name="report",
            name="result_text",
            field=models.TextField(
                blank=True,
                help_text="Free-text test result entered by the technologist",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("VERIFIED", "Verified"),
                    ("DELIVERED", "Delivered"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="reports/"),
        ),
        migrations.AlterField(
            model_name="report",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelTable(
            name="centertestpricing",
            table="apps_center_test_pricing",
        ),
        migrations.AlterModelTable(
            name="report",
            table="apps_report",
        ),
        migrations.AlterModelTable(
            name="testtype",
            table="apps_test_type",
        ),
        migrations.CreateModel(
            name="TestOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("NORMAL", "Normal"), ("URGENT", "Urgent")],
                        default="NORMAL",
                        max_length=10,
                    ),
                ),
                (
                    "clinical_notes",
                    models.TextField(
                        blank=True, help_text="Doctor notes for the lab technician"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_orders",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_orders",
                        to="tenants.diagnosticcenter",
                    ),
                ),
                (
                    "ordered_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The doctor who ordered this test",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ordered_tests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "test_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="diagnostics.testtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "test order",
                "verbose_name_plural": "test orders",
                "db_table": "apps_test_order",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="report",
            name="test_order",
            field=models.OneToOneField(
                blank=True,
                help_text="The test order this report fulfills",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report",
                to="diagnostics.testorder",
            ),
        ),
    ]
