# Generated by Django 6.0.2 on 2026-03-08 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_remove_pending_status'),
        ('diagnostics', '0004_add_test_order_and_enhance_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testorder',
            name='ordered_by',
        ),
        migrations.AddField(
            model_name='testorder',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who entered this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_test_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testorder',
            name='patient',
            field=models.ForeignKey(default=1, help_text='The patient this test is for', on_delete=django.db.models.deletion.CASCADE, related_name='test_orders', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testorder',
            name='referring_doctor_name',
            field=models.CharField(blank=True, help_text='Name of the external doctor who prescribed the test', max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='report',
            name='test_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='diagnostics.testorder'),
        ),
        migrations.AlterField(
            model_name='testorder',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_orders', to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='testorder',
            name='clinical_notes',
            field=models.TextField(blank=True, help_text='Notes from prescription or doctor'),
        ),
    ]
