# Generated by Django 6.0.2 on 2026-03-09 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diagnostics", "0006_seed_bangladeshi_tests"),
        ("tenants", "0006_add_phone_number_and_patient_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferringDoctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Full name, e.g. "Dr. Aminul Islam"', max_length=255
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "MBBS, FCPS (Medicine)"',
                        max_length=255,
                    ),
                ),
                (
                    "institution",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Dhaka Medical College Hospital"',
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referring_doctors",
                        to="tenants.diagnosticcenter",
                    ),
                ),
            ],
            options={
                "verbose_name": "referring doctor",
                "verbose_name_plural": "referring doctors",
                "db_table": "apps_referring_doctor",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fields",
                    models.JSONField(
                        help_text='List of field definitions: [{"name": "...", "unit": "...", "ref_range": "..."}]'
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "test_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_template",
                        to="diagnostics.testtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "report template",
                "verbose_name_plural": "report templates",
                "db_table": "apps_report_template",
            },
        ),
    ]
