# Generated by Django 6.0.2 on 2026-03-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diagnostics", "0008_seed_report_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
