# Generated by Django 6.0 on 2026-03-10 12:28

import uuid
from django.db import migrations, models


def generate_unique_access_tokens(apps, schema_editor):
    """Generate unique UUIDs for existing reports."""
    Report = apps.get_model('diagnostics', 'Report')
    for report in Report.objects.all():
        report.access_token = uuid.uuid4()
        report.save(update_fields=['access_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0016_fill_gender_age_ref_ranges'),
    ]

    operations = [
        # Step 1: Add fields without unique constraint
        migrations.AddField(
            model_name='report',
            name='access_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='access_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When the report was verified', null=True),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='fields',
            field=models.JSONField(help_text='List of field definitions: [{"name": "...", "unit": "...", "ref_range": "..." or "ref_range_male": "...", "ref_range_female": "...", "ref_range_child": "..."}]'),
        ),
        # Step 2: Generate unique tokens for existing rows
        migrations.RunPython(generate_unique_access_tokens, migrations.RunPython.noop),
        # Step 3: Now make it unique + non-nullable
        migrations.AlterField(
            model_name='report',
            name='access_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token for public report access', unique=True),
        ),
    ]
