# Generated by Django 6.0.2 on 2026-03-30 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0025_diagnosticcenter_send_email_invoice_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AICreditUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("REPORT_EXTRACTION", "Report Extraction"),
                            ("CHATBOT_SESSION", "Chatbot Session"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "credits_used",
                    models.IntegerField(
                        default=1, help_text="Number of credits consumed by this task"
                    ),
                ),
                (
                    "input_tokens",
                    models.IntegerField(
                        default=0, help_text="Tokens sent to the AI model"
                    ),
                ),
                (
                    "output_tokens",
                    models.IntegerField(
                        default=0, help_text="Tokens received from the AI model"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extra context: report_id, test_type, etc.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_credit_logs",
                        to="tenants.diagnosticcenter",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI credit usage log",
                "verbose_name_plural": "AI credit usage logs",
                "db_table": "apps_ai_credit_usage_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
