# Generated by Django 6.0.2 on 2026-03-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_add_lab_technician_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=1,
            ),
        ),
    ]
